apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra.default.svc
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      datacenter: "datacenter3"
      mode: "test"
      timeout: "3m"