apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "cassandra"
  claimRef:
    name: cassandra-pvc
    namespace: default
  nfs:
    server: 10.240.0.54
    path: /smtbrc
