apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "cassandra"
  resources:
    requests:
      storage: 10Gi
